### ISSUE TITLE
swisseph-api won't run

### ISSUE THREAD

**Issue by miquael** [mivion/swisseph-api#1]
$:swisseph-api mac$ npm start

> swisseph-api@0.1.0 start /Users/mac/_INTRA/_APPS/AION/ephemeris_engines/swisseph-api
> node ./bin/server

module.js:338
    throw err;
          ^
Error: Cannot find module 'serve-favicon'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/mac/_INTRA/_APPS/AION/ephemeris_engines/swisseph-api/app.js:3:15)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)

npm ERR! Darwin 12.5.0
npm ERR! argv "node" "/usr/local/bin/npm" "start"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE
npm ERR! swisseph-api@0.1.0 start: `node ./bin/server`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the swisseph-api@0.1.0 start script 'node ./bin/server'.
npm ERR! This is most likely a problem with the swisseph-api package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/server
npm ERR! You can get their info via:
npm ERR!     npm owner ls swisseph-api
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/mac/_INTRA/_APPS/AION/ephemeris_engines/swisseph-api/npm-debug.log
$:swisseph-api mac$ node --version
v0.12.0

$:swisseph-api mac$ node app.js
module.js:338
    throw err;
          ^
Error: Cannot find module 'serve-favicon'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/mac/_INTRA/_APPS/AION/ephemeris_engines/swisseph-api/app.js:3:15)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
$:swisseph-api mac$

**Comment by miquael** [comment]
npm imstall 

(!!!)

**Comment by mivion** [comment]
Before run you have to:

> npm install

in project folder.
Does it start now?

**Comment by miquael** [comment]
yes, it works!  thank you ~

**Comment by miquael** [comment]
... er ... well, it was working perfectly yesterday.  now the page comes up at localhost:3000, but there are no body numbers showing.

**Comment by mivion** [comment]
I have commited some changes. Check this out.
Also checkout the http://swisseph.com, this is online working version.
